export type Certification = {
  id: number;
  title: string;
  issuer: string;
  date: string;
  image: string;
  credentialUrl: string;
  description: string;
};

export const certifications: Certification[] = [
  {
    id: 1,
    title: "National Registry Emergency Medical Technician (NREMT)",
    issuer: "National Registry of Emergency Medical Technicians",
    date: "Apr 2026 — Active",
    image: "",
    credentialUrl: "#",
    description: "Active NREMT certification (EMS ID: 3668-4546-3129) with 56+ hours of clinical field experience across hospital ER and pre-hospital EMS environments.",
  },
  {
    id: 2,
    title: "FERPA — Family Educational Rights and Privacy Act",
    issuer: "Purdue University",
    date: "Aug 2025 — Active",
    image: "",
    credentialUrl: "#",
    description: "Certified in student educational record privacy rights, permissible disclosures, and institutional compliance obligations under FERPA.",
  },
  {
    id: 3,
    title: "HIPAA — Health Insurance Portability and Accountability Act",
    issuer: "Purdue University",
    date: "Aug 2025 — Active",
    image: "",
    credentialUrl: "#",
    description: "Certified in protected health information (PHI) handling, patient privacy rights, and healthcare data security compliance under HIPAA.",
  },
  {
    id: 4,
    title: "GLBA — Gramm-Leach-Bliley / Financial Services Modernization Act",
    issuer: "Purdue University",
    date: "Aug 2025 — Active",
    image: "",
    credentialUrl: "#",
    description: "Certified in financial data privacy obligations, safeguarding consumer information, and institutional compliance under the Gramm-Leach-Bliley Act.",
  },
  {
    id: 5,
    title: "Data Classification and Handling",
    issuer: "Purdue University",
    date: "Aug 2025 — Active",
    image: "",
    credentialUrl: "#",
    description: "Demonstrates proficiency in institutional data classification tiers, handling requirements, and secure data management best practices.",
  },
  {
    id: 6,
    title: "Protecting Social Security Numbers",
    issuer: "Purdue University",
    date: "Aug 2025 — Active",
    image: "",
    credentialUrl: "#",
    description: "Certified in proper handling, storage, and protection of Social Security Numbers in compliance with university policy and federal requirements.",
  },
  {
    id: 7,
    title: "Claude 101",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Foundational course covering Claude's capabilities, core principles, and best practices for effective human-AI collaboration.",
  },
  {
    id: 8,
    title: "Claude Code 101",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Introductory course on Claude Code, Anthropic's AI-powered CLI tool for software engineering tasks directly in the terminal.",
  },
  {
    id: 9,
    title: "Introduction to Claude at Work",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Practical introduction to integrating Claude into professional workflows to enhance productivity and decision-making in workplace settings.",
  },
  {
    id: 10,
    title: "Claude Code in Action",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Hands-on course demonstrating real-world applications of Claude Code for software development, debugging, and agentic coding tasks.",
  },
  {
    id: 11,
    title: "AI Fluency: Framework & Foundations",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Comprehensive framework for understanding AI systems, responsible use principles, and foundational concepts for navigating the AI landscape.",
  },
  {
    id: 12,
    title: "Building with the Claude API",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Technical course on integrating the Claude API into applications, covering authentication, prompt engineering, and production deployment patterns.",
  },
  {
    id: 13,
    title: "Introduction to Model Context Protocol",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Introduction to MCP, an open standard for connecting AI models to external tools, data sources, and services in a standardized way.",
  },
  {
    id: 14,
    title: "AI Fluency for Educators",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Specialized course equipping educators with AI literacy skills, pedagogical strategies, and frameworks for responsibly incorporating AI into educational environments.",
  },
  {
    id: 15,
    title: "AI Fluency for Students",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Course designed to help students develop AI literacy, critical thinking around AI outputs, and skills for effective academic use of AI tools.",
  },
  {
    id: 16,
    title: "Claude with Google Cloud's Vertex AI",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Technical course on deploying and scaling Claude models via Google Cloud's Vertex AI platform for enterprise-grade AI applications.",
  },
  {
    id: 17,
    title: "Teaching AI Fluency",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Advanced course on instructional design and curriculum development for teaching AI fluency concepts to diverse learner populations.",
  },
  {
    id: 18,
    title: "AI Fluency for Nonprofits",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Tailored AI fluency training for nonprofit professionals, covering mission-aligned AI use, resource considerations, and responsible adoption strategies.",
  },
  {
    id: 19,
    title: "Introduction to Agent Skills",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Introduction to building and deploying Claude Agent Skills — reusable, composable capabilities that extend Claude's functionality in agentic workflows.",
  },
  {
    id: 20,
    title: "Introduction to Subagents",
    issuer: "Anthropic Academy",
    date: "Apr 2026",
    image: "",
    credentialUrl: "#",
    description: "Course covering the design and orchestration of subagents within multi-agent systems, enabling complex task delegation and parallel AI workflows.",
  },
];
